### ISSUE TITLE
"This content is unavailable." when trying to play random songs

### ISSUE THREAD

**Issue by subnut** [OpenByteDev/BurntSushi#8] opened 2021-12-22 16:23 UTC
When Spotify initially starts up, I can play any random song from any playlist/album/etc.

But after some time.... When I go to play some random song from a playlist, the song (_all_ of the songs) are greyed out. Double-clicking them to play causes Spotify to show _This content is not available._ in a blue popup box above the Now Playing panel.

i.e. I can't play songs randomly from a playlist, but can play the playlist as a whole.

Why is this happening?

This is a recent phenomenon.... maybe since the start of this month.  
Previously this wasn't happening.

Closing and re-opening Spotify seems to resolve it, but after some time, it again happens.

**Comment by OpenByteDev** [comment] 2021-12-28 16:56
I cannot currently reproduce the error in Spotify 1.1.74.631.g0b24d9ad and BurntSushi v0.3.1:

Are you using the newest version of Spotify and BurntSushi?
How long does it usually take for the error to occur?

**Comment by subnut** [comment] 2021-12-29 04:49
Sorry, I am currently not using my Windows machine (it's been sent for repairing) and won't be able to give any feedback.

I will close this issue for now, and will re-open if I see this behavior again, with some time measurements and the corresponding logs.

**Comment by OpenByteDev** [comment] 2022-01-15 18:59
I just encountered this bug on my own, though replicating and fixing it may take a while.

**Comment by OpenByteDev** [comment] 2022-01-15 19:09
This seems to be the same issue as https://github.com/abba23/spotify-adblock/issues/60.

**Comment by OpenByteDev** [comment] 2022-01-21 21:10
Fixed in [v0.3.2](https://github.com/OpenByteDev/BurntSushi/releases/tag/0.3.2)

**Closed as completed by OpenByteDev** 2022-01-21 21:10 UTC
Labels: bug
